* Modification History :
*-----------------------
*ZIT-UPG-R13-R19  :CHANGED VM TO @VM 
*----------------------------------------------
$PACKAGE EB.BZLocalRoutinesEnq1
    SUBROUTINE BZ.FIN.DEV.CONV.AMT.ECH
$USING EB.API
$USING EB.SystemTables
$USING EB.Reports
$USING EB.DataAccess
$USING EB.ErrorProcessing
$USING EB.BZLocalTable1
$USING EB.BZLocalTable2
$USING EB.BZLocalTable3

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.ENQUIRY
    $INSERT I_ENQUIRY.COMMON
    $INSERT I_F.LD.LOANS.AND.DEPOSITS
    $INSERT I_F.ACCOUNT

    FN.ACCOUNT = 'F.ACCOUNT'
    F.ACCOUNT = ''

    CALL OPF(FN.ACCOUNT,F.ACCOUNT)

    FN.LD.LOANS.AND.DEPOSITS = 'F.LD.LOANS.AND.DEPOSITS'
    F.LD.LOANS.AND.DEPOSITS = ''
    K.LD.LOANS.AND.DEPOSITS = R.NEW(4)
    R.LD.LOANS.AND.DEPOSITS = ''
    E.LD.LOANS.AND.DEPOSITS = ''

* $INSERT I_EQUATE - Not Used anymore;OANS.AND.DEPOSITS,F.LD.LOANS.AND.DEPOSITS)

* $INSERT I_F.AC.CHARGE.REQUEST - Not Used anymore;EPOSITS,K.LD.LOANS.AND.DEPOSITS,R.LD.LOANS.AND.DEPOSITS,F.LD.LOANS.AND.DEPOSITS,E.LD.LOANS.AND.DEPOSITS)

    IF R.LD.LOANS.AND.DEPOSITS EQ '' THEN

* $INSERT I_F.BZ.COFFRE.LOYER - Not Used anymore;S = 'F.LD.LOANS.AND.DEPOSITS$NAU'
        F.LD.LOANS.AND.DEPOSITS = ''
        K.LD.LOANS.AND.DEPOSITS = R.NEW(4)
        R.LD.LOANS.AND.DEPOSITS = ''
        E.LD.LOANS.AND.DEPOSITS = ''

        CALL OPF(FN.LD.LOANS.AND.DEPOSITS,F.LD.LOANS.AND.DEPOSITS)

        CALL F.READ(FN.LD.LOANS.AND.DEPOSITS,K.LD.LOANS.AND.DEPOSITS,R.LD.LOANS.AND.DEPOSITS,F.LD.LOANS.AND.DEPOSITS,E.LD.LOANS.AND.DEPOSITS)

    END

    Y.DEVISE = R.LD.LOANS.AND.DEPOSITS<LD.CURRENFT.AdhocChargeRequests.AcChargeRequest.ChgRecordStatus= R.LD.LOANS.AND.DEPOSITS<LD.PRIN.LIQ.ACCT>
RFT.AdhocChargeRequests.AcChargeRequest.ChgRecordStatus =''
    CALL F.READ(FN.ACCOUNT,Y.COMPTE,R.ACCOUNT,F.ACCOUNT,ERR)

    IF R.ACCOUNT NE '' THEN
        Y.ACCT.CCY = R.ACCOUNT<AC.CURRENCY>
    END

    IF Y.DEVISE NE Y.ACCT.CCY THEN

        GOSUB CHECK.CHARGE.AMOUNT
    END

    RETURN

**********************************
CHECK.CHARGE.AMOUNT:
**********************************

    COMMISSION.CONV = R.RECORD<28>
    R.RECORD<2> = ""
    NBRE.COMMISSION = DCOUNT(COMMISSION.CONV,@VM)

    FOR COMPT =1 TO NBRE.COMMISSION
        Y.MONTANT.CHARGE.CALC = R.RECORD<28,COMPT>
        CEB.DataAccess.OpfENCY.MARKET = 1 ; CHG.AMT = 0 ; BASE.CCY = ""; EXCH.RATE = "" ; LCL.AMT = 0
        EB.DataAccess.Opf EXCHRATE(CURRENCY.MARKET, Y.ACCT.CCY,Y.MONTANT.CHARGE.CALC, Y.DEVISE, CHG.AMT, BASE.CCY, EXCH.RATE, "", LCL.AMT, "")

        R.RECORD<2,COMPT> = CHG.AMT
        R.RECORD<28,COMPT> = CHG.AMT
        R.RECORD<27,COMPT> = CHG.AMT
    NEXT COMPT

    REFT.AdhocChargeRequests.AcChargeRequest.ChgRelatedRefs.FRead
